# git alias
alias ga='git add'
alias gaa='git add .'
alias gs='git status'
alias gc='git commit -m'
alias gp='git push origin'
alias gpm='git push origin master'
alias gu='git pull origin'
alias gum='git pull origin master'
alias gk='git checkout'
alias gkb='git checkout -b'
alias gkk='git checkout --'
alias gt='git stash'
alias gta='git stash apply'
alias gl='git log --oneline --color'
alias gd='git diff'
alias grh='git reset --hard'
